### ISSUE TITLE
Feature-Request: "Save raw-data to csv"

### ISSUE THREAD

**Issue by DocSneider** [kiwih/agilent-rs232#3]
Hello and thanks a lot for your work! :smiley: :+1: 

I have not practice in programming python, so I wanted to ask you if it would be possible to add a button on the plot screen or a option for the command line, to tell the script that it should save the "raw data".

Maybe the easiest way would be to pass a command-line-option like:

     --export /FILE/PATH/file.csv , -e /FILE/PATH/file.csv  export the raw data-points to a csv-file

That way it would be easy to work with the measurements in other tools or software.

Thanks in advance :smiley:

**Comment by kiwih** [comment]
Hi there, I currently don't have access to the agilent scope so don't want to alter the code at this time, but you could consider just dumping the contents of data_points (e.g. add a `print(data_points)`, which might get what you want with regards to dumping the contents of the array to the console and then you can copy and paste into other applications. Otherwise, I direct you to https://docs.python.org/3/library/csv.html - always a good time to learn something new!
